### PR TITLE
(MCOP-598) Add service provider for the service command

### PR DESCRIPTION
**Pull request by nhuff**
Add a provider that calls the service command to start, stop, restart and
get process status.  The location of the service command defaults to
/sbin/service but is configurable by setting
plugin.service.service.servicecmd to the path of the command.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This looks like a good start, but I have some concerns around error handling and correctness on the service commands. I'd also like to see testing, and you haven't signed our CLA. Do you have any interest in following up to improve this pull request? If not, or if I don't hear anything in the next month, I'm going to close it.

**Comment by MikaelSmith** [comment]
Also, why do you feel this is necessary over Puppet's service provider?

**Comment by nhuff** [comment]
I don't use puppet so the puppet service provider doesn't work for me.

**Comment by MikaelSmith** [comment]
Filed https://tickets.puppetlabs.com/browse/MCOP-598. This isn't broadly portable, but since many people only work on a few operating systems I don't see a reason to avoid having OS-specific implementations available.

**Pull request merged**
